package org.musicservice.demo.error;

public enum ErrorType {
    API_ERROR, USER_NOT_FOUND_ERROR, VALIDATION_ERROR, REGISTRATION_ERROR,
    INVALID_DATE_FORMAT, INVALID_BODY_REQUEST, MISSING_MUSIC_CONTENT, MUSIC_GENRE_DOES_NOT_EXIST;
}
