security:
  login:
    max-failed-attempts: 3      # Максимальное число неудачных попыток входа
    lock-duration-minutes: 15   # Время в минутах, на которое блокируется аккаунт при достижении максимального числа попыток входа


yandex:
  access-key: "YCAJEZWueSbh5sYY5pVWj1y2E"
  secret-key: "YCNjDrXSEl9jH62FRplhdZsiNHpwfH0orTSXhqY5"
  buckets:
    music: "mus-app-tracks"
    img: "mus-app-img"
  region: "ru-central1"
  endpoint: "https://storage.yandexcloud.net"
  default-avatar-key: "default_avatar.jpg"

jamendo:
  client-id: 9dc3f71a

jwt:
  jwt-secret-key: cd0353d9c7bde503904336bfb85fd34d
  issuer: app-name
  leeway-seconds: 30
  access-token-duration: PT1M

refresh-token:
  duration: P30D

verification-token:
  expiration-hours: PT24H
  activation-url: "http://localhost:8080/api/auth/activate?token="

cookie:
  refresh-token: "refreshToken"