spring.application.name=MusicService

# Data Source
spring.datasource.url=jdbc:postgresql://localhost:5432/MusicService
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=syperklik55

# Thymeleaf
spring.thymeleaf.check-template-location=false

# Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true

# Java Mail Sender
spring.mail.host=smtp.gmail.com
spring.mail.password=pjfb waxb yhxo nfnr
spring.mail.port=587
spring.mail.username=igor.bocharov.77@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

