spring.application.name=MusicService

# Data Source
spring.datasource.url=jdbc:postgresql://localhost:5432/MusicService
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=syperklik55

# Thymeleaf
spring.thymeleaf.check-template-location=false

# Hibernate
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt_secret_key=cd0353d9c7bde503904336bfb85fd34d

# Value
expiration_hours=PT24H

# Java Mail Sender
spring.mail.host=smtp.gmail.com
spring.mail.password=pjfb waxb yhxo nfnr
spring.mail.port=587
spring.mail.username=igor.bocharov.77@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

activation_url=http://localhost:8080/api/auth/activate?token=
